name: app

services:
  mysql:
    image: mysql:${MYSQL_IMAGE_TAG}
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports: ["3306:3306"]
    healthcheck: # https://github.com/docker-library/mysql/issues/930
      test:
        [
          "CMD-SHELL",
          "mysqladmin --silent -h localhost -u root -p'${MYSQL_ROOT_PASSWORD}' ping",
        ]
      interval: 10s
      timeout: 10s
      retries: 30

  redis:
    image: redis:${REDIS_IMAGE_TAG}
    command:
      - --maxmemory
      - 1gb
      - --maxmemory-policy
      - allkeys-lru
      - --requirepass
      - ${REDIS_PASSWORD} # https://docs.docker.com/compose/compose-file/12-interpolation/
    restart: always
    volumes:
      - redis_data:/data # https://github.com/redis/docker-library-redis/issues/140
    ports: ["6379:6379"]
    healthcheck: # https://github.com/redis/docker-library-redis/issues/91
      test: ["CMD-SHELL", "redis-cli -a '${REDIS_PASSWORD}' ping"]
      interval: 10s
      timeout: 10s
      retries: 30

  server:
    image: ghcr.io/whoisnian/tracing-benchmark:${SERVER_IMAGE_TAG}
    restart: always
    profiles: ["default"]
    environment:
      - CFG_LISTEN_ADDR=0.0.0.0:8080
      - CFG_MYSQL_DSN=${CFG_MYSQL_DSN}
      - CFG_REDIS_URI=${CFG_REDIS_URI}
      - CFG_TRACE_OTLP_ENDPOINT=${CFG_TRACE_OTLP_ENDPOINT}
      - CFG_TRACE_APM_ENDPOINT=${CFG_TRACE_APM_ENDPOINT}
      - CFG_TRACE_APM_SECRET_TOKEN=${CFG_TRACE_APM_SECRET_TOKEN}
      - CFG_TRACE_ZIPKIN_ENDPOINT=${CFG_TRACE_ZIPKIN_ENDPOINT}
      - CFG_TRACE_BACKEND=${CFG_TRACE_BACKEND}
    ports: ["8080:8080"]
    extra_hosts: # https://github.com/moby/moby/blob/42f40b1d6dd7562342f832b9cd2adf9e668eeb76/daemon/container_operations.go#L118
      - host.docker.internal:host-gateway
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    cpus: '4.000'
    mem_limit: 4gb

  server-sw:
    image: ghcr.io/whoisnian/tracing-benchmark-sw:${SERVER_IMAGE_TAG}
    restart: always
    profiles: ["skywalking"]
    environment:
      - CFG_LISTEN_ADDR=0.0.0.0:8080
      - CFG_MYSQL_DSN=${CFG_MYSQL_DSN}
      - CFG_REDIS_URI=${CFG_REDIS_URI}
      - CFG_TRACE_BACKEND=${CFG_TRACE_BACKEND}
      - SW_AGENT_NAME=${SW_AGENT_NAME}
      - SW_AGENT_REPORTER_GRPC_BACKEND_SERVICE=${SW_AGENT_REPORTER_GRPC_BACKEND_SERVICE}
    ports: ["8080:8080"]
    extra_hosts: # https://github.com/moby/moby/blob/42f40b1d6dd7562342f832b9cd2adf9e668eeb76/daemon/container_operations.go#L118
      - host.docker.internal:host-gateway
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    cpus: '4.000'
    mem_limit: 4gb

volumes:
  mysql_data: {}
  redis_data: {}
