{
 "title": "cAdvisor",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "compose_project",
    "query": {
     "query": "label_values(container_last_seen{image!=\"\"},container_label_com_docker_compose_project)"
    }
   },
   {
    "name": "container_name",
    "query": {
     "query": "label_values(container_last_seen{image!=\"\"},name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "cpu usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{image!=\"\",container_label_com_docker_compose_project=~\"$compose_project\",name=~\"$container_name\"}[20s])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "memory usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{image!=\"\",container_label_com_docker_compose_project=~\"$compose_project\",name=~\"$container_name\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "network in (bytes)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{image!=\"\",container_label_com_docker_compose_project=~\"$compose_project\",name=~\"$container_name\"}[20s])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "network out (bytes)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(container_network_transmit_bytes_total{image!=\"\",container_label_com_docker_compose_project=~\"$compose_project\",name=~\"$container_name\"}[20s])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "network in (packets)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(container_network_receive_packets_total{image!=\"\",container_label_com_docker_compose_project=~\"$compose_project\",name=~\"$container_name\"}[20s])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "network out (packets)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(container_network_transmit_bytes_total{image!=\"\",container_label_com_docker_compose_project=~\"$compose_project\",name=~\"$container_name\"}[20s])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "fs read (bytes)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(container_fs_reads_bytes_total{image!=\"\",container_label_com_docker_compose_project=~\"$compose_project\",name=~\"$container_name\"}[20s])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "fs write (bytes)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(container_fs_writes_bytes_total{image!=\"\",container_label_com_docker_compose_project=~\"$compose_project\",name=~\"$container_name\"}[20s])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "fs read (ops)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(container_fs_reads_total{image!=\"\",container_label_com_docker_compose_project=~\"$compose_project\",name=~\"$container_name\"}[20s])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "fs write (ops)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(container_fs_writes_total{image!=\"\",container_label_com_docker_compose_project=~\"$compose_project\",name=~\"$container_name\"}[20s])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}