name: jaeger

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    restart: always
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    environment:
      - node.name=es
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - ELASTIC_PASSWORD=${JAEGER_ELASTIC_PASSWORD}
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=false
    # ports: ["9200:9200"]
    healthcheck: # https://github.com/elastic/elasticsearch/blob/8.15/docs/reference/setup/install/docker/docker-compose.yml
      test:
        [
          "CMD-SHELL",
          "curl -s http://localhost:9200 | grep -q 'missing authentication credentials'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120

  collector:
    image: jaegertracing/jaeger-collector:1.60
    restart: always
    environment:
      - SPAN_STORAGE_TYPE=elasticsearch
      - ES_SERVER_URLS=http://elasticsearch:9200
      - ES_USERNAME=elastic
      - ES_PASSWORD=${JAEGER_ELASTIC_PASSWORD}
    ports: # https://www.jaegertracing.io/docs/1.60/deployment/#collector
      - 4317:4317 # OTLP over gRPC
      - 4318:4318 # OTLP over HTTP
    healthcheck: # https://github.com/jaegertracing/jaeger/blob/0524ae6df8acac17e8ed52af9b86e6dee85a5e5e/cmd/internal/status/command.go
      test: ["CMD-SHELL", "/go/bin/collector-linux status"]
      interval: 10s
      timeout: 10s
      retries: 30
    depends_on:
      elasticsearch:
        condition: service_healthy

  query:
    image: jaegertracing/jaeger-query:1.60
    restart: always
    environment:
      - SPAN_STORAGE_TYPE=elasticsearch
      - ES_SERVER_URLS=http://elasticsearch:9200
      - ES_USERNAME=elastic
      - ES_PASSWORD=${JAEGER_ELASTIC_PASSWORD}
    ports: # https://www.jaegertracing.io/docs/1.60/deployment/#query-service--ui
      - 16686:16686 # serve frontend
    healthcheck: # https://github.com/jaegertracing/jaeger/blob/0524ae6df8acac17e8ed52af9b86e6dee85a5e5e/cmd/internal/status/command.go
      test: ["CMD-SHELL", "/go/bin/query-linux status"]
      interval: 10s
      timeout: 10s
      retries: 30
    depends_on:
      elasticsearch:
        condition: service_healthy

volumes:
  elasticsearch_data: {}
