name: jaeger

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTICSEARCH_IMAGE_TAG}
    restart: always
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    environment:
      - node.name=es
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - ELASTIC_PASSWORD=${JAEGER_ELASTIC_PASSWORD}
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=false
    # ports: ["9200:9200"]
    healthcheck: # https://github.com/elastic/elasticsearch/blob/8.15/docs/reference/setup/install/docker/docker-compose.yml
      test:
        [
          "CMD-SHELL",
          "curl -s http://localhost:9200 | grep -q 'missing authentication credentials'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120
    cpus: '2.000'
    mem_limit: 4gb

  jaeger:
    image: jaegertracing/jaeger:${JAEGER_IMAGE_TAG}
    restart: always
    environment:
      - GOMAXPROCS=2
      - ES_SERVER_URL=http://elasticsearch:9200
      - ES_USERNAME=elastic
      - ES_PASSWORD=${JAEGER_ELASTIC_PASSWORD}
    volumes:
      - ./config.yaml:/cmd/jaeger/config.yaml
    tmpfs:
      - /tmp
    command: ["--config", "/cmd/jaeger/config.yaml"]
    ports: # https://www.jaegertracing.io/docs/2.1/apis/#default-ports
      - 4317:4317 # OTLP over gRPC
      - 4318:4318 # OTLP over HTTP
      - 8888:8888 # curl -s 127.0.0.1:8888/metrics | grep '_spans{'
      - 16686:16686 # extension: jaeger_query
      # - 13133:13133 # extension: healthcheckv2
    healthcheck: # https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/v0.115.0/extension/healthcheckv2extension/README.md
      test: ["CMD-SHELL", "wget --quiet --tries=1 --spider http://localhost:13133/status || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 30
    depends_on:
      elasticsearch:
        condition: service_healthy
    cpus: '2.000'
    mem_limit: 4gb

volumes:
  elasticsearch_data: {}
