name: release

on:
  push:
    tags: ["v*"]

jobs:
  build-binaries:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"
          check-latest: true
          cache: true

      - name: Setup SkyWalking Go Agent
        run: |
          wget -P /tmp https://dlcdn.apache.org/skywalking/go/0.5.0/apache-skywalking-go-0.5.0-bin.tgz
          tar -xvf /tmp/apache-skywalking-go-0.5.0-bin.tgz -C /tmp
          cp /tmp/apache-skywalking-go-0.5.0-bin/bin/skywalking-go-agent-0.5.0-linux-amd64 /usr/local/bin/skywalking-go-agent

      - name: Build binaries
        run: bash -ex ./build/build.sh all && bash -ex ./build/build.sh all-sw

      - name: Upload release
        uses: softprops/action-gh-release@v1
        with:
          files: output/*
          generate_release_notes: true
